# Generated by Django 2.1.5 on 2019-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_historicalemployeelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
    ]
