# Generated by Django 2.1.5 on 2019-01-30 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeLabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Default Rate')),
                ('estimated_time', models.IntegerField(verbose_name='Default Estimated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountType', verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Account Labor Settings',
                'verbose_name_plural': 'Account Labor Settings',
                'ordering': ['account_type__name', 'labor_type__name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTypeServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Default Rate')),
                ('estimated_time', models.IntegerField(verbose_name='Default Estimated Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountType', verbose_name='Account Type')),
            ],
            options={
                'verbose_name': 'Account Service Settings',
                'verbose_name_plural': 'Account Service Settings',
                'ordering': ['account_type__name', 'service_type__name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Invoice Number')),
                ('receive_date', models.DateField(verbose_name='Received')),
                ('complete_date', models.DateField(blank=True, null=True, verbose_name='Completed')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('make', models.CharField(blank=True, max_length=20, null=True, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('stock_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stock Number')),
                ('po_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='PO Number')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is Complete')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Tax Rate')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.Account', verbose_name='Account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical invoice',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInvoiceType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Invoice Type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLaborType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Labor Type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServiceType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Service Type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Invoice Number')),
                ('receive_date', models.DateField(verbose_name='Received')),
                ('complete_date', models.DateField(blank=True, null=True, verbose_name='Completed')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('make', models.CharField(blank=True, max_length=20, null=True, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('stock_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stock Number')),
                ('po_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='PO Number')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is Complete')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Tax Rate')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Account', verbose_name='Account')),
            ],
            options={
                'ordering': ['invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Invoice Type',
                'verbose_name_plural': 'Invoice Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_rate', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Estimated Rate')),
                ('actual_rate', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Actual Rate')),
                ('estimated_time', models.IntegerField(verbose_name='Estimated Time')),
                ('actual_time', models.IntegerField(verbose_name='Estimated Time')),
                ('labor_date', models.DateField(verbose_name='Labor Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee', verbose_name='Employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labor',
                'ordering': ['labor_date', 'invoice__invoice_number', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Labor Type',
                'verbose_name_plural': 'Labor Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Rate')),
                ('estimated_time', models.IntegerField(verbose_name='Estimated Time')),
                ('service_date', models.DateField(verbose_name='Service Date')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
                'ordering': ['service_date', 'invoice__invoice_number', 'service_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.ServiceType', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='labor',
            name='labor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.LaborType', verbose_name='Labor Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.InvoiceType', verbose_name='Invoice Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='invoice_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoice.InvoiceType', verbose_name='Invoice Type'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employee.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='accounttypeservices',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ServiceType', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='accounttypelabor',
            name='labor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.LaborType', verbose_name='Labor Type'),
        ),
    ]
