# Generated by Django 2.1.5 on 2019-02-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_created=True, verbose_name='Log Date')),
                ('stock_number', models.CharField(max_length=20, verbose_name='Stock Number')),
                ('note', models.CharField(max_length=160, verbose_name='Note')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Vehicle Log',
                'verbose_name_plural': 'Vehicle Log',
                'ordering': ['-log_date'],
            },
        ),
    ]
