# Generated by Django 2.1.5 on 2019-02-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_vehiclelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='invoice.Invoice', verbose_name='Invoice'),
        ),
    ]
