# Generated by Django 2.1.5 on 2019-02-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190223_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttypelabor',
            options={'verbose_name': 'Service-Labor Mapping', 'verbose_name_plural': 'Service-Labor Mapping'},
        ),
        migrations.AlterModelOptions(
            name='labor',
            options={'verbose_name': 'Labor', 'verbose_name_plural': 'Labor'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='vehiclelog',
            options={'ordering': ['-id'], 'verbose_name': 'Vehicle Log', 'verbose_name_plural': 'Vehicle Log'},
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='stock_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Stock Number'),
        ),
    ]
