# Generated by Django 2.1.5 on 2019-03-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20190223_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor', to='invoice.Invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='service',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='invoice.Invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='invoice.Invoice', verbose_name='Invoice'),
        ),
    ]
