# Generated by Django 2.1.5 on 2019-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20190309_1036'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['vin'], name='ix_invoice_vin'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stock_number'], name='ix_invoice_stock_number'),
        ),
    ]
